//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.29 at 04:25:21 AM IST 
//


package org.visitor.core;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.visitor.core.visitors package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class VisitorsInfoFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.visitor.core.visitors
     * 
     */
    public VisitorsInfoFactory() {
    }

    /**
     * Create an instance of {@link VisitorsInfo.Nameinfo }
     * 
     */
    public VisitorsInfo.Nameinfo createRestnamesNameinfo() {
        return new VisitorsInfo.Nameinfo();
    }

    /**
     * Create an instance of {@link VisitorsInfo.Nameinfo.Name }
     * 
     */
    public VisitorsInfo.Nameinfo.Name createRestnamesNameinfoName() {
        return new VisitorsInfo.Nameinfo.Name();
    }

    /**
     * Create an instance of {@link VisitorsInfo }
     * 
     */
    public VisitorsInfo createRestnames() {
        return new VisitorsInfo();
    }

}
